 							 <td>{{$buku -> id_buku}}</td><br>
                            <td>{{$buku -> judul}}</td><br>
                            <td>{{$buku -> noisbn}}</td><br>
                            <td>{{$buku -> penulis}}</td><br>
                            <td>{{$buku -> penerbit}}</td><br>
                            <td>{{$buku -> tahun}}</td><br>
                            <td>{{$buku -> stok}}</td><br>
                            <td>{{$buku -> harga_pokok}}</td><br>
                            <td>{{$buku -> harga_jual}}</td><br>
                            <td>{{$buku -> ppn}}</td><br>
                            <td>{{$buku -> diskon}}</td><br>